version: 2.1
orbs:
  node: circleci/node@4.7.0
commands:
  print_branch_cmd:
    steps:
      - run:
          name: "current branch"
          command: echo ${CIRCLE_BRANCH}

  install_deps_cmd:
    steps:
      - checkout
      - run: npm install

  build_gh_pages_cmd:
    steps:
      - run: echo "starting checkout"
      - checkout
      - run: echo "finished checkout"
      - run: echo "starting build"
      - run: npm run build:gh-pages
      - run: echo "finished build"

  deploy_gh_pages_cmd:
    - run: echo "build production project"
    - run: npm run build:production
    - run: echo "generate static production project"
    - run: npm run generate:production
    - run: echo "deploy production static project to github"
    - run: npm run deploy:production

jobs:
  build-gh-pages:
    docker:
      - image: cimg/node:lts
    steps:
      - print_branch_cmd
      - install_deps_cmd
      - build_gh_pages_cmd
  deploy-gh-pages:
    docker:
      - image: cimg/node:lts
    steps:
      - deploy_gh_pages_cmd

workflows:
  deploy-gh-pages:
    jobs:
      - build-gh-pages
      - deploy-gh-pages:
          requires:
            - build-gh-pages
          filters:
            branches:
              only: main
