version: 2.1
orbs:
  node: circleci/node@4.7.0

commands:
  checkout_and_install:
    description: "Checkout code and install dependencies"
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  build_project:
    description: "Build the project"
    parameters:
      build_command:
        type: string
    steps:
      - run:
          name: Build Project
          command: npm run << parameters.build_command >>

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout_and_install
      - build_project:
          build_command: "build:gh-pages"
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - dist

  deploy:
    docker:
      - image: cimg/node:lts
    steps:
      - run:
          name: Set Node Options
          command: echo 'export NODE_OPTIONS=--openssl-legacy-provider' >> $BASH_ENV
      - checkout_and_install
      - build_project:
          build_command: "build:gh-pages"
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - dist
      - run:
          name: Deploy Project
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              npm run deploy:gh-pages
            fi

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
          filters:
            branches:
              not: main
      - deploy:
          filters:
            branches:
              only: main
