version: 2.1
orbs:
  node: circleci/node@3.0.0
commands:
  print_branch_cmd:
    steps:
      - run:
          name: "current branch"
          command: echo ${CIRCLE_BRANCH}

  install_deps_cmd:
    steps:
      - checkout
      - run: npm install

  build_gh_pages_cmd:
    steps:
      - run: echo "starting checkout"
      - checkout
      - run: echo "finished checkout"
      - run: echo "starting build"
      - run: npm run build:gh-pages
      - run: echo "finished build"

jobs:
  build-gh-pages:
    steps:
      - print_branch_cmd
      - install_deps_cmd
      - build_gh_pages_cmd

workflows:
  deploy-gh-pages:
    jobs:
      - build-gh-pages
